import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
               Random generator = new Random(seed);  
               int 2child =0;
               int 3child =0;
               int 4OrMore=0;
               int sumChild=0;
               for( int i=0 ; i<T ; i++) {
                   int bCount=0 ;
                   int gCount=0;
                   while (bCount<1 || gCount<1) {
                       double rand= genarator.nextDouble();
                       boolean sex= ( rand< 0.5 ) ;
                       if ( sex) {
                           bCount++;           
                     } else {
                          gCount++;
              }
           
        }     
                   if ( bCount+gCount==2)
                       2child++;
                   if ( bCount+gCount==3)
                       3child++;
                   if (bCount+gCount >= 4)
                      4OrMore++;
                   sumChild= sumChild + bCount + gCount ;

               }
            double avg= (sumChild / 1.0) / T ;
            System.out.println("Average: " + avg + " children to get at least one of each gender.");
	    System.out.println("Number of families with 2 children: " + 2child);	
            System.out.println("Number of families with 2children: " + 3child);	
            System.out.println("Number of families with 4 or more children: " + 4OrMore);
		    
	}
}
